pull_request_rules:
  - name: Merge approved and green PRs with merge-when-green label
    conditions:
      - "#approved-reviews-by>=2"
      - status-success=Continuous Integration
      - base=develop
      - label=merge when green
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
        commit_message: title+body
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Continuous Integration
      - base=develop
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
        commit_message: title+body
    