pull_request_rules:
  - name: Merge approved and green PRs without merge blocking PR labels
    conditions:
      - "#approved-reviews-by>=2"
      - label!=["WIP", "Don't merge", "On hold"]
      - check-success=Deploy
      - base=develop
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
        commit_message: title+body
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - "#approved-reviews-by>=0"
      - label!=["WIP", "Don't merge", "On hold"]
      - check-success=Deploy
      - base=develop
    actions:
      merge:
        method: squash
        strict: smart+fasttrack
        commit_message: title+body
    